[tox]
requires =
    tox>=4.53.0
    tox-uv>=1.35.1
env_list =
    lint
    py312

[testenv]
description = Run tests and generate coverage reports
dependency_groups = dev
commands =
    pytest --cov=optichat {posargs:tests/}

[testenv:lint]
description = Run Ruff to analyze code and enforce style
dependency_groups = dev
commands =
    ruff check .
    ruff format --check .
